### ISSUE TITLE
How to make youtube player responsive?

### ISSUE THREAD

**Issue by sakhmedbayev** [troybetz/react-youtube#118]
How I can make `<YouTube />` component responsive?

**Comment by cfey** [comment]
Try this
```jsx
<div class="videoWrapper">
    <YouTube ... />
</div>
```

with this style
```css
.videoWrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
	overflow: hidden;
}
.videoWrapper iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}
```

see [here](http://embedresponsively.com/)
